### ISSUE TITLE
非常规导航的`命令模式`实现

### ISSUE THREAD

**Issue by BBSQQ** [jiazhewang/Weekly-Notes#1]
> 使用设计模式是为了可重用代码、让代码更容易被他人理解、保证代码可靠性。

在平时的业务场景中可能你也不经意的用到了一些设计模式，可能你的某些冗余难以调整的代码正式某种设计模式可以解决的...

本文正式基于真实业务场景，利用命令模式中的宏命令方式将代码重构，提高了代码的可读性和可操作性。

https://www.yuque.com/docs/share/2132936a-35fb-43ce-9281-1c7907bbe2d3

**Comment by jiazhewang** [comment]
已经采纳，感谢！

**Comment by jiazhewang** [comment]
收录至 w1：others
