### ISSUE TITLE
Graph Theory Course

### ISSUE THREAD

**Issue by BBSQQ** [jiazhewang/Weekly-Notes#2]
Link: [Graph Theory by Sarada Herke](https://www.youtube.com/playlist?list=PLoJC20gNfC2gmT_5WgwYwGMvgCjYVsIQg)

Recommended reason: 
* Although the course is taught in English, professional concepts are easier to understand when expressed in English, such as degree and isomorphism.
* Theory combined with practice by [saga](https://cloud.sagemath.com/)

**Comment by jiazhewang** [comment]
Could u introduce a little about the tool [CoCalc](https://cocalc.com/) linked from your saga hyperlink?

**Comment by BBSQQ** [comment]
OK. It is more appropriate to name the program notebook [CoCalc](https://cocalc.com/). 
CoCalc (formerly called SageMathCloud) is a web-based cloud computing (SaaS) and course management platform for computational mathematics. 
**CoCalc is a part of the Sage project.**
So what is the Sage(SageMath) project? It is a computer algebra system with features covering many aspects of mathematics, including algebra, combinatorics, graph theory, numerical analysis, number theory, calculus and statistics. You can click [this](https://en.wikipedia.org/wiki/SageMath) to get the list of Software packages contained in SageMath

**Comment by jiazhewang** [comment]
Perfect! thx!
The Graph Theory videos had been added to note of week2.
CoCalc has been added to note of week3.
